version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: trakr-postgres
    environment:
      POSTGRES_DB: trakr
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trakr-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/trakr?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run dev"

volumes:
  postgres_data: