version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: trakr-mysql
    environment:
      MYSQL_DATABASE: trakr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: